//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by JCClass.rc
//
#define IDS_DATABASE_VERSION_ERROR      1
#define SIZE_IDB_DELETE                 20
#define IDB_TRACKER                     101
#define IDC_NS_BUTTON                   102
#define IDC_NC_COMBO                    103
#define IDC_SCROLLH                     105
#define IDC_SCROLLV                     106
#define IDC_SPREADSHEET_CONTROL         107
#define IDC_NE_EDIT                     108
#define IDC_CCW_BUTTON                  109
#define IDC_SS_MINILIST                 113
#define IDD_PROCESSING                  131
#define IDC_COLUMN_CURSOR               154
#define IDC_NO_ENTRY                    155
#define IDB_DNARROW                     159
#define IDB_UPARROW                     160
#define IDD_RECORD_SELECTOR             200
#define IDC_TSE_TOOLBAR                 260
#define IDR_TEXSETEDIT                  261
#define IDC_MAGNIFY                     262
#define IDC_DRAG                        264
#define IDC_DRAG_MULTIPLE               265
#define IDD_CUSTOMISE_SPREADSHEET       300
#define IDB_DEFAULT                     414
#define IDB_DELETE                      415
#define IDB_CUSTOMISE                   416
#define IDD_TSE_GRID                    417
#define IDC_HAND                        418
#define IDD_TSE_PROP                    419
#define IDB_TSE_PALGROUP_TOOLBAR        420
#define IDD_TSE_PALGROUP_EDIT           421
#define IDD_TSE_PROP_ITEM               422
#define IDC_NOGRID                      423
#define IDC_CUSTOM_X_LABEL              424
#define IDC_CUSTOM_X                    425
#define IDC_CUSTOM_Y_LABEL              426
#define IDC_PROGRESS                    1001
#define IDC_CAPTION                     1002
#define IDC_OUTPUT                      1003
#define IDC_HELPLINE3                   1008
#define IDC_HELPLINE4                   1009
#define IDC_HELPLINE1                   1010
#define IDC_HELPLINE2                   1011
#define IDC_SPREADSHEET                 1013
#define IDC_RECORDLIST                  1070
#define IDC_SS_COLUMNNAME               1071
#define IDC_GRID8X8                     1611
#define IDC_GRID8X16                    1612
#define IDC_GRID16X8                    1613
#define IDC_GRID16X16                   1614
#define IDC_GRID_CUSTOMSIZE             1615
#define IDC_CUSTOM_Y                    1616
#define IDC_SNAPTOGRID                  1617
#define IDC_SHOW_SNAPGRID               1618
#define IDC_CUSTOM_SIZE_GROUP           1619
#define IDC_SHOW_PIXELGRID              1620
#define IDC_TSE_LIST1                   1621
#define IDC_TSE_COLOUR_PAD              1622
#define IDC_TSE_CUSTOM1                 1623
#define IDC_TSE_EDIT_PALGROUP_NAME      1624
#define IDC_TSE_EDIT1                   1625
#define IDC_TSE_EDIT_PALGROUP_BMP       1626
#define IDC_TSE_BUTTON2                 1627
#define IDC_TSE_BUTTON1                 1628
#define IDC_TSE_CHECK1                  1629
#define IDC_TSE_COMBO1                  1630
#define IDC_TSE_EDIT2                   1631
#define IDC_TSE_EDIT3                   1632
#define IDC_TSE_STATIC1                 1633
#define IDC_TSE_STATIC2                 1634
#define ID_CHOICE_MENU_START            2000
#define ID_CHOICE_MENU_END              2999
#define ID_MINIDATAMENU_START           3000
#define ID_MINIDATAMENU_END             3999
#define ID_TSE_PROP_COLMENU_START       4000
#define ID_TSE_PROP_COLMENU_END         4999
#define ID_TSE_PALGROUP_NEW             33136
#define ID_TSE_PALGROUP_FIRST           33137
#define ID_TSE_PALGROUP_EDIT            33138
#define ID_TSE_PALGROUP_DELETE          33139

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
